import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navigation/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_BASEURL || "http://localhost:3000"),
  keywords: ["Invoice App", "Phuti Sekwadi Projects", "Trymichel Phuti Sekwadi", "Get Invoice", "Free invoice", "Invoice Template"],
  title: {
    default: "GetInvoice",
    template: "%s | GetInvoice"
  },
  description: "Generated by Phuti Sekwadi",
  openGraph: {
    description: "GetInvoice is a free online invoicing software that helps you write and print invoices for your customers for free! Share with others",
    images: '/image/phuti_ico.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
